name: Frontend Code Quality Checks

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Frontend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'Frontend/**'

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'Frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: Frontend

    - name: Run ESLint
      run: npm run lint
      working-directory: Frontend

    - name: Run Prettier
      run: npm run format-check
      working-directory: Frontend